dbt_superstore:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      user: analytics
      password: analytics
      port: 5432
      dbname: superstore
      schema: analytics
      threads: 4